services:
  db:
    image: "postgres:17"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$DATABASE_NAME -U $$POSTGRES_USER"]
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build:
      context: .
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      TIME_ZONE: ${TIME_ZONE}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    ports:
      - "8000:8000"

volumes:
  db:
    external: true