# Generated by Django 5.1 on 2024-08-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_texted',
            new_name='question_text',
        ),
    ]
