# Generated by Django 5.1 on 2024-08-31 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0002_rename_question_texted_question_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name='date published'),
        ),
    ]
